services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      # - /app/node_modules
      - .:/app

  redis:
    image: "redis:alpine"